-- Times do Coração da Timemania (80 times)
-- Dados obtidos de: https://silce.carrinho.caixa.gov.br/loterias-web/carrinho/v1/publico/parametros-simulacao/
INSERT INTO time_timemania (codigo_caixa, nome, uf, nome_completo, ativo) VALUES
(293, 'ABC', 'RN', 'ABC/RN', true),
(805, 'ALTOS', 'PI', 'ALTOS/PI', true),
(333, 'AMAZONAS', 'AM', 'AMAZONAS/AM', true),
(38, 'AMERICA', 'MG', 'AMERICA/MG', true),
(40, 'AMERICA', 'RN', 'AMERICA/RN', true),
(389, 'APARECIDENSE', 'GO', 'APARECIDENSE/GO', true),
(830, 'ATHLETIC CLUB', 'MG', 'ATHLETIC CLUB/MG', true),
(22, 'ATHLETICO', 'PR', 'ATHLETICO/PR', true),
(143, 'ATLETICO', 'GO', 'ATLETICO/GO', true),
(3, 'ATLETICO', 'MG', 'ATLETICO/MG', true),
(18, 'AVAI', 'SC', 'AVAI/SC', true),
(20, 'BAHIA', 'BA', 'BAHIA/BA', true),
(499, 'BAHIA DE FEIRA', 'BA', 'BAHIA DE FEIRA/BA', true),
(298, 'BOTAFOGO', 'PB', 'BOTAFOGO/PB', true),
(2, 'BOTAFOGO', 'RJ', 'BOTAFOGO/RJ', true),
(42, 'BOTAFOGO', 'SP', 'BOTAFOGO/SP', true),
(157, 'BRAGANTINO', 'SP', 'BRAGANTINO/SP', true),
(232, 'BRASIL DE PELOTAS', 'RS', 'BRASIL DE PELOTAS/RS', true),
(21, 'BRASILIENSE', 'DF', 'BRASILIENSE/DF', true),
(302, 'BRUSQUE', 'SC', 'BRUSQUE/SC', true),
(297, 'CAMPINENSE', 'PB', 'CAMPINENSE/PB', true),
(951, 'CASCAVEL', 'PR', 'CASCAVEL/PR', true),
(43, 'CAXIAS', 'RS', 'CAXIAS/RS', true),
(34, 'CEARA', 'CE', 'CEARA/CE', true),
(75, 'CEILANDIA ESPORTE', 'DF', 'CEILANDIA ESPORTE/DF', true),
(250, 'CHAPECOENSE', 'SC', 'CHAPECOENSE/SC', true),
(138, 'CONFIANCA', 'SE', 'CONFIANCA/SE', true),
(10, 'CORINTHIANS', 'SP', 'CORINTHIANS/SP', true),
(13, 'CORITIBA', 'PR', 'CORITIBA/PR', true),
(44, 'CRB', 'AL', 'CRB/AL', true),
(19, 'CRICIUMA', 'SC', 'CRICIUMA/SC', true),
(24, 'CRUZEIRO', 'MG', 'CRUZEIRO/MG', true),
(340, 'CSA', 'AL', 'CSA/AL', true),
(609, 'CUIABA', 'MT', 'CUIABA/MT', true),
(342, 'FERROVIARIA', 'SP', 'FERROVIARIA/SP', true),
(145, 'FERROVIARIO', 'CE', 'FERROVIARIO/CE', true),
(23, 'FIGUEIRENSE', 'SC', 'FIGUEIRENSE/SC', true),
(4, 'FLAMENGO', 'RJ', 'FLAMENGO/RJ', true),
(824, 'FLORESTA', 'CE', 'FLORESTA/CE', true),
(11, 'FLUMINENSE', 'RJ', 'FLUMINENSE/RJ', true),
(9, 'FORTALEZA', 'CE', 'FORTALEZA/CE', true),
(8, 'GOIAS', 'GO', 'GOIAS/GO', true),
(29, 'GREMIO', 'RS', 'GREMIO/RS', true),
(31, 'GUARANI', 'SP', 'GUARANI/SP', true),
(25, 'INTERNACIONAL', 'RS', 'INTERNACIONAL/RS', true),
(35, 'ITUANO', 'SP', 'ITUANO/SP', true),
(820, 'JACUIPENSE', 'BA', 'JACUIPENSE/BA', true),
(759, 'JUAZEIRENSE', 'BA', 'JUAZEIRENSE/BA', true),
(28, 'JUVENTUDE', 'RS', 'JUVENTUDE/RS', true),
(47, 'LONDRINA', 'PR', 'LONDRINA/PR', true),
(821, 'MANAUS', 'AM', 'MANAUS/AM', true),
(311, 'MIRASSOL', 'SP', 'MIRASSOL/SP', true),
(16, 'NAUTICO', 'PE', 'NAUTICO/PE', true),
(150, 'NOVA IGUACU', 'RJ', 'NOVA IGUACU/RJ', true),
(808, 'NOVORIZONTINO', 'SP', 'NOVORIZONTINO/SP', true),
(556, 'OESTE', 'SP', 'OESTE/SP', true),
(526, 'OPERARIO', 'PR', 'OPERARIO/PR', true),
(1, 'PALMEIRAS', 'SP', 'PALMEIRAS/SP', true),
(12, 'PARANA', 'PR', 'PARANA/PR', true),
(14, 'PAYSANDU', 'PA', 'PAYSANDU/PA', true),
(5, 'PONTE PRETA', 'SP', 'PONTE PRETA/SP', true),
(149, 'PORTUGUESA', 'RJ', 'PORTUGUESA/RJ', true),
(831, 'POUSO ALEGRE', 'MG', 'POUSO ALEGRE/MG', true),
(49, 'REMO', 'PA', 'REMO/PA', true),
(958, 'RETRO BRASIL', 'PE', 'RETRO BRASIL/PE', true),
(364, 'SAMP CORREA', 'MA', 'SAMP CORREA/MA', true),
(50, 'SANTA CRUZ', 'PE', 'SANTA CRUZ/PE', true),
(27, 'SANTOS', 'SP', 'SANTOS/SP', true),
(76, 'SAO BERNARDO', 'SP', 'SAO BERNARDO/SP', true),
(551, 'SAO JOSE', 'RS', 'SAO JOSE/RS', true),
(6, 'SAO PAULO', 'SP', 'SAO PAULO/SP', true),
(934, 'SAORAIMUNDO', 'RR', 'SAORAIMUNDO/RR', true),
(33, 'SPORT', 'PE', 'SPORT/PE', true),
(215, 'TOCANTINOPOLIS', 'TO', 'TOCANTINOPOLIS/TO', true),
(653, 'TOMBENSE', 'MG', 'TOMBENSE/MG', true),
(7, 'VASCO DA GAMA', 'RJ', 'VASCO DA GAMA/RJ', true),
(53, 'VILA NOVA', 'GO', 'VILA NOVA/GO', true),
(15, 'VITORIA', 'BA', 'VITORIA/BA', true),
(55, 'VOLTA REDONDA', 'RJ', 'VOLTA REDONDA/RJ', true),
(656, 'YPIRANGA', 'RS', 'YPIRANGA/RS', true)
ON CONFLICT (codigo_caixa) DO UPDATE SET
    nome = EXCLUDED.nome,
    uf = EXCLUDED.uf,
    nome_completo = EXCLUDED.nome_completo,
    ativo = EXCLUDED.ativo;
